# NOTE: not migrating other settings into this file yet as I don't know how
# well they'd play with our 'dual doc trees' setup. But the below should apply
# to both equally.
version: 2

build:
  # Specific version of RTD docker image that's new enough to have Rust around
  # (so Cryptography can build from source if needed).
  # See https://github.com/readthedocs/readthedocs-docker-images
  image: "7.0"
